### ISSUE TITLE
Can the jailbreak results be made public? 

### ISSUE THREAD

**Issue by yyytwo** [usail-hkust/JailTrickBench#4]

**Comment by zhaoxu98** [comment]
Hi, Thank you for your interest in our work and for raising this issue! 

We do plan to make the relevant jailbreak results public. Currently, we are assessing the compliance for releasing these results. Additionally, some of the results are used in our [recent work](https://github.com/usail-hkust/Jailjudge), and the related annotated datasets are publicly available here: 

- HuggingFace Dataset: https://huggingface.co/datasets/usail-hkust/JailJudge. 
- Paper: https://arxiv.org/abs/2410.12855
- Github Repo: https://github.com/usail-hkust/Jailjudge

Feel free to check out some examples or use the dataset if needed!
