### ISSUE TITLE
Clarification about Figure 6(a)

### ISSUE THREAD

**Issue by krishnakanthnakkav2** [usail-hkust/JailTrickBench#5]
Dear Authors, 

Thank you for comprehensive experiments.

I have a question about the Figure 6(a) regarding the impact the attacker ability. Can you please clarify what are the target models in this ablation, and which attack method is used in here?

I understand along the x-axis is the attacker LLM architectures but it is not clear about target model and target attack type?

Thanks in advance.

**Comment by krishnakanthnakkav2** [comment]
Nevermind, this script https://github.com/usail-hkust/JailTrickBench/blob/main/scripts/2_trick_atk_ability_pair.sh suggest it is PAIR and attack model is L2-7B. Can you kindly confirm if my understanding is right.

Thanks

**Comment by zhaoxu98** [comment]
Hi, 

Thank you for your interest in our work and for raising this issue!

In the script [here](https://github.com/usail-hkust/JailTrickBench/blob/main/scripts/2_trick_atk_ability_pair.sh), we evaluate the impact of different attackers with varying abilities. The target model used is `Llama2-7b-chat-hf`, while the attack models include `vicuna-13b-v1.5`, `Llama-2-13b-chat-hf`, `GPT-3.5-Turbo`, and `GPT-4`.
